export const FETCH_ALL_DATA = 'FETCH_ALL_DATA';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FILTER_DEPARTMENTS = 'FILTER_DEPARTMENTS';
export const SELECT_DEPARTMENTS = 'SELECT_DEPARTMENTS';
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
